project_name: thermite
before:
  hooks:
    - go mod tidy
    - go mod vendor
    - go build ./...
    - go fmt ./...
    - go vet ./...
    - go test ./...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
    goos:
      - darwin
      - linux
      - windows
archives:
  - builds:
    - thermite
brews:
  - tap:
      owner: dollarshaveclub
      name: "homebrew-public"
    folder: Formula
    homepage: "https://github.com/dollarshaveclub/thermite"
    description: "Removes old Amazon Elastic Container Registry images that are not deployed in a Kubernetes cluster"
    license: "MIT"
dockers:
  -
    image_templates:
    - "dollarshaveclub/{{.ProjectName}}:{{.Major}}"
    - "dollarshaveclub/{{.ProjectName}}:{{.Major}}.{{.Minor}}"
    - "dollarshaveclub/{{.ProjectName}}:{{.Major}}.{{.Minor}}.{{.Patch}}"
    - "dollarshaveclub/{{.ProjectName}}:latest"
    extra_files:
    - cmd/
    - pkg/
    - vendor/
    - go.mod
    - go.sum
    - main.go