# TODO: Document requirements for running goreleaser
project_name: thermite
before:
  hooks:
    - go get -u ./...
    - go mod tidy
    - go mod vendor
    - go build ./...
    - go fmt ./...
    - go vet ./...
    - go test ./...
    - go run doc/doc.go
    - helm package charts/thermite --destination=.cr-release-packages
    - cr upload --git-repo=helm-charts-public --owner dollarshaveclub
    - cr index --charts-repo=https://dollarshaveclub.github.io/helm-charts-public/ --git-repo helm-charts-public --owner dollarshaveclub --push
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
    goos:
      - darwin
      - linux
      - windows
archives:
  - builds:
    - thermite
brews:
  - tap:
      owner: dollarshaveclub
      name: "homebrew-public"
    folder: Formula
    homepage: "https://github.com/dollarshaveclub/thermite"
    description: "Removes old Amazon Elastic Container Registry images that are not deployed in a Kubernetes cluster"
    license: "MIT"
dockers:
  -
    image_templates:
    - "dollarshaveclub/{{.ProjectName}}:{{.Tag}}"
    - "dollarshaveclub/{{.ProjectName}}:v{{.Major}}"
    - "dollarshaveclub/{{.ProjectName}}:v{{.Major}}.{{.Minor}}"
    - "dollarshaveclub/{{.ProjectName}}:latest"
    extra_files:
    - cmd/
    - pkg/
    - vendor/
    - go.mod
    - go.sum
    - main.go