version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/dollarshaveclub/thermite
    steps:
      - checkout
      - run: go build -v ./...
  test:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/dollarshaveclub/thermite
    steps:
      - checkout
      - run: go vet -v ./...
      - run: go test -v ./...
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test